### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by erichaus** [nickschot/ember-mobile-core#3]
Hello, I saw your talk at emberconf and am interested in the work on this, particularly the "android-like" slideout navigation menu and the tabbed navigation, which I have immediate need for.

Have you prepared any documentation for this package or any of the other ones you mentioned?

Thanks for all the work!

**Comment by nickschot** [comment]
The menu has basic documentation available in the [README](https://github.com/nickschot/ember-mobile-menu). The other packages (bar/pane/core) will get documentation soon. They're all relatively easy to use though. Examples are of course in the [example app](https://github.com/nickschot/emberconf2018). 

If you have any more specific questions or need some help, feel free to ping me on the ember slack!

**Comment by erichaus** [comment]
ok great thanks!
